//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionOnline.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionStatu
    {
        public int ASID { get; set; }
        public int AuctionID { get; set; }
        public int AccountID { get; set; }
        public decimal BidPrice { get; set; }
        public System.DateTime BidTime { get; set; }
    
        public virtual Auction Auction { get; set; }
    }
}
